#!/usr/bin/env python3
"""fixture/generate_dump.py — Generate the fixture DB dump from production.

Run this once against the live JobSlicer DB, then sanitize and compress:

    python fixture/generate_dump.py \\
        --db-url postgresql://jobslicer:slicerpass@localhost:5432/jobslicer \\
        > fixture/dump_raw.sql

    python fixture/sanitize.py fixture/dump_raw.sql > fixture/dump_clean.sql
    gzip -9 -c fixture/dump_clean.sql > fixture/dump.sql.gz

What is included:
    market.jobs_raw          — rows WHERE description IS NOT NULL
                               raw_json column is EXCLUDED (large, private)
    market.jobs_derived      — rows joined to the above jobs_raw rows
    market.companies         — all companies that have company_scores rows
    market.company_scores    — all scores for the above companies
    market.job_skills_premium  — empty (output table)
    market.company_scores_premium — empty (output table)

What is NOT included:
    raw_json column — contains the full scraped JSON payload (can include PII)
    Any table outside the market schema
    Any FK to auth.users (enriched_by_user_id is set to NULL)

The dump is self-contained: it creates the market schema and all tables from
scratch, without requiring the full JobSlicer schema to exist first.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from typing import Any

import sqlalchemy as sa
from sqlalchemy import text


# ---------------------------------------------------------------------------
# DDL — minimal schema for the fixture
# These match the current production schema (migration 018).
# ---------------------------------------------------------------------------

DDL = """\
-- fixture/dump.sql
-- Generated by fixture/generate_dump.py
-- Load order: market.companies → market.company_scores
--             market.jobs_raw → market.jobs_derived
--             (output tables dumped empty)

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE SCHEMA IF NOT EXISTS market;

-- Sequences (owner reset at end of file)
CREATE SEQUENCE IF NOT EXISTS market.jobs_raw_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS market.jobs_derived_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS market.companies_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS market.company_scores_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS market.job_skills_premium_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS market.company_scores_premium_id_seq START 1;

-- market.companies
CREATE TABLE IF NOT EXISTS market.companies (
    id              INTEGER PRIMARY KEY DEFAULT nextval('market.companies_id_seq'),
    name            TEXT NOT NULL,
    name_key        TEXT NOT NULL UNIQUE,
    domain          TEXT,
    industry        TEXT,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- market.company_scores
CREATE TABLE IF NOT EXISTS market.company_scores (
    id                INTEGER PRIMARY KEY DEFAULT nextval('market.company_scores_id_seq'),
    company_id        INTEGER NOT NULL REFERENCES market.companies(id),
    role_domain       VARCHAR(50) NOT NULL,
    tier              VARCHAR(20) NOT NULL DEFAULT 'standard',
    trust_score       INTEGER,
    trust_label       VARCHAR(20),
    hiring_score      INTEGER,
    hiring_label      VARCHAR(20),
    signals           JSON,
    bullet_points     JSON,
    metrics           JSON,
    computed_at       TIMESTAMPTZ DEFAULT now(),
    reanalyze_due_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    verdicts          JSON,
    company_domain    VARCHAR(50),
    large_brand       BOOLEAN,
    UNIQUE (company_id, role_domain)
);
CREATE INDEX IF NOT EXISTS ix_company_scores_company_id
    ON market.company_scores (company_id);

-- market.jobs_raw  (raw_json excluded — too large and may contain PII)
CREATE TABLE IF NOT EXISTS market.jobs_raw (
    id                      INTEGER PRIMARY KEY DEFAULT nextval('market.jobs_raw_id_seq'),
    source                  VARCHAR(50),
    job_id                  VARCHAR(255),
    title                   TEXT,
    company                 TEXT,
    city                    TEXT,
    state                   TEXT,
    location                TEXT,
    job_type                VARCHAR(50),
    interval                VARCHAR(50),
    min_amount              NUMERIC,
    max_amount              NUMERIC,
    currency                VARCHAR(10),
    url                     TEXT,
    description             TEXT,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    search_location         TEXT,
    is_processed            BOOLEAN DEFAULT false,
    is_discarded            BOOLEAN DEFAULT false,
    is_company_derived      BOOLEAN NOT NULL DEFAULT false,
    date_posted             TIMESTAMPTZ,
    last_seen_in_scrape_at  TIMESTAMPTZ,
    rescan_due_at           TIMESTAMPTZ,
    country_code            VARCHAR(2) NOT NULL DEFAULT 'XX'
);

-- market.jobs_derived
CREATE TABLE IF NOT EXISTS market.jobs_derived (
    id                INTEGER PRIMARY KEY DEFAULT nextval('market.jobs_derived_id_seq'),
    job_fk            INTEGER NOT NULL REFERENCES market.jobs_raw(id),
    section_about     TEXT,
    section_salary    TEXT,
    section_skills    TEXT,
    section_job_type  TEXT,
    section_contract  TEXT,
    created_at        TIMESTAMPTZ DEFAULT now(),
    human_verified    BOOLEAN,
    role_domain       VARCHAR(50),
    skill_tokens      JSON,
    llm_reparsed_at   TIMESTAMPTZ,
    is_demo_candidate BOOLEAN NOT NULL DEFAULT false
);

-- market.job_skills_premium (output — loaded empty, populated by job_skills task)
CREATE TABLE IF NOT EXISTS market.job_skills_premium (
    id                  INTEGER PRIMARY KEY DEFAULT nextval('market.job_skills_premium_id_seq'),
    job_fk              INTEGER NOT NULL UNIQUE REFERENCES market.jobs_raw(id),
    required            JSON,
    preferred           JSON,
    enriched_by_user_id INTEGER,  -- FK to auth.users omitted (not in fixture)
    enriched_at         TIMESTAMPTZ,
    reanalyze_due_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- market.company_scores_premium (output — loaded empty, populated by company_enrich task)
CREATE TABLE IF NOT EXISTS market.company_scores_premium (
    id                  INTEGER PRIMARY KEY DEFAULT nextval('market.company_scores_premium_id_seq'),
    company_id          INTEGER NOT NULL REFERENCES market.companies(id),
    role_domain         VARCHAR(50) NOT NULL DEFAULT '__all__',
    llm_result          JSON,
    enriched_by_user_id INTEGER,  -- FK to auth.users omitted (not in fixture)
    enriched_at         TIMESTAMPTZ,
    reanalyze_due_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, role_domain)
);

"""

SEQUENCE_RESETS = """\
-- Reset sequences to max(id) so INSERTs after loading don't collide
SELECT setval('market.jobs_raw_id_seq',
    COALESCE((SELECT MAX(id) FROM market.jobs_raw), 0) + 1, false);
SELECT setval('market.jobs_derived_id_seq',
    COALESCE((SELECT MAX(id) FROM market.jobs_derived), 0) + 1, false);
SELECT setval('market.companies_id_seq',
    COALESCE((SELECT MAX(id) FROM market.companies), 0) + 1, false);
SELECT setval('market.company_scores_id_seq',
    COALESCE((SELECT MAX(id) FROM market.company_scores), 0) + 1, false);
"""


# ---------------------------------------------------------------------------
# SQL literal helpers
# ---------------------------------------------------------------------------

def _lit(v: Any) -> str:
    """Return a SQL literal for value v."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime):
        return f"'{v.isoformat()}'"
    s = str(v)
    # Standard SQL escaping: double single-quotes
    s = s.replace("'", "''")
    return f"'{s}'"


def _write_inserts(
    out,
    table: str,
    columns: list[str],
    rows: list,
    batch: int = 200,
) -> None:
    """Write batched INSERT statements to out."""
    if not rows:
        out.write(f"-- {table}: 0 rows\n\n")
        return

    out.write(f"-- {table}: {len(rows)} rows\n")
    col_list = ", ".join(columns)

    for start in range(0, len(rows), batch):
        chunk = rows[start : start + batch]
        out.write(f"INSERT INTO {table} ({col_list}) VALUES\n")
        value_lines = []
        for row in chunk:
            vals = ", ".join(_lit(row[c]) for c in columns)
            value_lines.append(f"  ({vals})")
        out.write(",\n".join(value_lines))
        out.write("\nON CONFLICT DO NOTHING;\n")

    out.write("\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate fixture DB dump from production."
    )
    parser.add_argument(
        "--db-url",
        default="postgresql://jobslicer:slicerpass@localhost:5432/jobslicer",
        help="Production DB connection URL.",
    )
    parser.add_argument(
        "--output",
        default="-",
        help="Output file path (default: stdout).",
    )
    args = parser.parse_args()

    engine = sa.create_engine(args.db_url)
    out = open(args.output, "w") if args.output != "-" else sys.stdout

    try:
        with engine.connect() as conn:
            _generate(conn, out)
    finally:
        if out is not sys.stdout:
            out.close()


def _generate(conn, out) -> None:
    out.write(DDL)

    # ── market.companies ────────────────────────────────────────────────────
    # Include all companies that have at least one company_scores row.
    result = conn.execute(
        text(
            "SELECT c.id, c.name, c.name_key, c.domain, c.industry, c.created_at "
            "FROM market.companies c "
            "WHERE EXISTS ("
            "  SELECT 1 FROM market.company_scores cs WHERE cs.company_id = c.id"
            ") "
            "ORDER BY c.id"
        )
    )
    companies = [dict(row._mapping) for row in result]
    print(f"[generate_dump] companies: {len(companies)}", file=sys.stderr)
    _write_inserts(
        out,
        "market.companies",
        ["id", "name", "name_key", "domain", "industry", "created_at"],
        companies,
    )

    company_ids = [c["id"] for c in companies]

    # ── market.company_scores ───────────────────────────────────────────────
    if company_ids:
        result = conn.execute(
            text(
                "SELECT id, company_id, role_domain, tier, trust_score, trust_label, "
                "       hiring_score, hiring_label, signals, bullet_points, metrics, "
                "       computed_at, reanalyze_due_at, verdicts, company_domain, large_brand "
                "FROM market.company_scores "
                "WHERE company_id = ANY(:ids) "
                "ORDER BY id"
            ),
            {"ids": company_ids},
        )
        cs_rows = [dict(row._mapping) for row in result]
    else:
        cs_rows = []
    print(f"[generate_dump] company_scores: {len(cs_rows)}", file=sys.stderr)
    _write_inserts(
        out,
        "market.company_scores",
        [
            "id", "company_id", "role_domain", "tier",
            "trust_score", "trust_label", "hiring_score", "hiring_label",
            "signals", "bullet_points", "metrics",
            "computed_at", "reanalyze_due_at", "verdicts",
            "company_domain", "large_brand",
        ],
        cs_rows,
    )

    # ── market.jobs_raw ─────────────────────────────────────────────────────
    # Exclude raw_json (large + may contain PII from the scraper payload).
    result = conn.execute(
        text(
            "SELECT id, source, job_id, title, company, city, state, location, "
            "       job_type, interval, min_amount, max_amount, currency, url, "
            "       description, created_at, search_location, is_processed, "
            "       is_discarded, is_company_derived, date_posted, "
            "       last_seen_in_scrape_at, rescan_due_at, country_code "
            "FROM market.jobs_raw "
            "WHERE description IS NOT NULL "
            "ORDER BY id"
        )
    )
    jobs_raw = [dict(row._mapping) for row in result]
    print(f"[generate_dump] jobs_raw: {len(jobs_raw)}", file=sys.stderr)
    _write_inserts(
        out,
        "market.jobs_raw",
        [
            "id", "source", "job_id", "title", "company", "city", "state",
            "location", "job_type", "interval", "min_amount", "max_amount",
            "currency", "url", "description", "created_at", "search_location",
            "is_processed", "is_discarded", "is_company_derived", "date_posted",
            "last_seen_in_scrape_at", "rescan_due_at", "country_code",
        ],
        jobs_raw,
    )

    job_ids = [r["id"] for r in jobs_raw]

    # ── market.jobs_derived ─────────────────────────────────────────────────
    if job_ids:
        # Check if is_demo_candidate column exists (migration 018 may not be applied yet)
        has_demo_col = conn.execute(
            text(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema='market' AND table_name='jobs_derived' "
                "AND column_name='is_demo_candidate'"
            )
        ).fetchone() is not None

        demo_select = ", is_demo_candidate" if has_demo_col else ", false AS is_demo_candidate"

        # Batch the query to avoid hitting any parameter limits
        derived_rows = []
        batch_size = 2000
        for start in range(0, len(job_ids), batch_size):
            chunk = job_ids[start : start + batch_size]
            result = conn.execute(
                text(
                    "SELECT id, job_fk, section_about, section_salary, section_skills, "
                    "       section_job_type, section_contract, created_at, "
                    "       human_verified, role_domain, skill_tokens, "
                    f"       llm_reparsed_at{demo_select} "
                    "FROM market.jobs_derived "
                    "WHERE job_fk = ANY(:ids) "
                    "ORDER BY id"
                ),
                {"ids": chunk},
            )
            derived_rows.extend([dict(row._mapping) for row in result])
    else:
        derived_rows = []
    print(f"[generate_dump] jobs_derived: {len(derived_rows)}", file=sys.stderr)
    _write_inserts(
        out,
        "market.jobs_derived",
        [
            "id", "job_fk", "section_about", "section_salary", "section_skills",
            "section_job_type", "section_contract", "created_at", "human_verified",
            "role_domain", "skill_tokens", "llm_reparsed_at", "is_demo_candidate",
        ],
        derived_rows,
    )

    # ── Output tables — empty ───────────────────────────────────────────────
    out.write("-- market.job_skills_premium: empty (output table)\n\n")
    out.write("-- market.company_scores_premium: empty (output table)\n\n")

    out.write(SEQUENCE_RESETS)

    total_jobs = len(jobs_raw)
    total_derived = len(derived_rows)
    total_companies = len(companies)
    total_cs = len(cs_rows)
    print(
        f"[generate_dump] Done. "
        f"jobs_raw={total_jobs} jobs_derived={total_derived} "
        f"companies={total_companies} company_scores={total_cs}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
